/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Chris Sweetwood (https://sketchfab.com/ChrisSweetwood)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/computer-terminal-b3a26b00c5b04eedad0a1cdca884130f
title: Computer Terminal
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ComputerTerminal(props) {
  const { nodes, materials } = useGLTF("../../models/computer_terminal/scene.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[18.16, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={212.25}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Comp_Screen000_TerminalMaterial_0.geometry}
              material={materials.TerminalMaterial}
            />
          </group>
          <group
            position={[0, -5.37, -41.87]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={120.57}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_ShadowMaterial_0.geometry}
              material={materials.ShadowMaterial}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_BackgroundMaterial_0.geometry}
              material={materials.BackgroundMaterial}
            />
          </group>
          <group
            position={[18.16, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={212.25}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Comp_Screen002_TerminalMaterial_0.geometry}
              material={materials.TerminalMaterial}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../../models/computer_terminal/scene.glb");
