/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dogflesh (https://sketchfab.com/dogflesh)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/retro-computer-9439cb5e09cc44caa63dfbfb299df45f
title: Retro computer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RetroWindows(props) {

  const { nodes, materials } = useGLTF("../../models/retro_computer_windows/scene.glb");
  
  console.log('Here are the materials: ', materials)

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.None}
          > <meshNormalMaterial wireframe={true} /></mesh>
        <mesh
          castShadow
          receiveShadow
          material={materials.None}
          geometry={nodes.Object_3.geometry}><meshNormalMaterial wireframe={true} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("../../models/retro_computer_windows/scene.glb");
